const produtos = [
  { "id": 4, "nome": "SABONETE LIQUIDO UVA 500ML", "preco": 5.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 5, "nome": "CONCENTRADO UBATUBA", "preco": 16.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 7, "nome": "REMOVEDOR PERFUMADO 500ML", "preco": 20.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 11, "nome": "PERFUME PARA ROUPAS 1 LITRO", "preco": 12.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 12, "nome": "AMACIANTE CONFORTO 2 LITROS", "preco": 10.00, "imagem": "img/amacft2.png", "categoria": "residencial" },
  { "id": 15, "nome": "PEDRA SANITARIA", "preco": 3.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 16, "nome": "DETERGENTE LIMAO 5 LITROS", "preco": 20.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 18, "nome": "CLORO GEL 5 LITROS", "preco": 29.90, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 19, "nome": "DESINFETANTE EUCALIPTO 5 LITROS", "preco": 11.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 21, "nome": "DESINFETANTE TALCO 5 LITROS", "preco": 11.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 24, "nome": "DESINFETANTE CAPIM LIMÃO 2 LITROS", "preco": 6.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 28, "nome": "SABAO LIQUIDO DE COCO 2 LITROS", "preco": 14.00, "imagem": "img/coco2l.png", "categoria": "residencial" },
  { "id": 32, "nome": "MARIDAO 2 LITROS", "preco": 10.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 33, "nome": "LIMPA VIDROS", "preco": 4.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 34, "nome": "ALCOOL PERFUMADO CEREJA E AVELÃ 2 LITROS", "preco": 10.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 37, "nome": "ALCOOL PERFUMADO BAMBOO 2 LITROS", "preco": 10.00, "imagem": "img/alcb2.png", "categoria": "residencial" },
  { "id": 39, "nome": "LIMPA AZULEJO REFIL", "preco": 13.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 41, "nome": "DIA DIA FLORAL", "preco": 9.90, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 47, "nome": "SABONETE LIQUIDO ERVA DOCE C VALVULA", "preco": 5.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 53, "nome": "SABAO CASEIRO", "preco": 5.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 55, "nome": "PASTA DE BRILHO 500GR", "preco": 7.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 57, "nome": "CHEIRINHO DIA DIA", "preco": 8.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 58, "nome": "MARIDAO 5 LITROS", "preco": 20.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 61, "nome": "MATA INSETOS 500ML VALVULA SPRAY", "preco": 15.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 72, "nome": "SABONETE LIQUIDO JASMIN 500ML", "preco": 3.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 73, "nome": "CANDIDA COLORIDA 2 LITROS", "preco": 7.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 76, "nome": "DESINFETANTE REVEILLON 2 LITROS", "preco": 6.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 77, "nome": "GEL SANITARIO", "preco": 3.99, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 80, "nome": "CLORO GEL 2 LITROS", "preco": 15.00, "imagem": "img/clorogel2l.png", "categoria": "residencial" },
  { "id": 82, "nome": "LUSTRA MOVEIS 500ML", "preco": 11.00, "imagem": "img/lm500.png", "categoria": "residencial" },
  { "id": 83, "nome": "VEJA SPARKLING", "preco": 3.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 87, "nome": "SABAO LIQUIDO ARIEX 2 LITROS", "preco": 14.00, "imagem": "img/ariex2l.png", "categoria": "residencial" },
  { "id": 95, "nome": "AMACIANTE DOWNIE 2 LITROS", "preco": 10.00, "imagem": "img/amad2l.png", "categoria": "residencial" },
  { "id": 98, "nome": "DESINFETANTE PINHO SOL 2 LITROS", "preco": 6.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 100, "nome": "VEJAX MULTIUSO 2 LITROS", "preco": 12.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 103, "nome": "SABAO LIQUIDO DINAMUS 2 LITROS", "preco": 14.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 118, "nome": "DESINFETANTE MAMAE BEBE 2 LITROS", "preco": 6.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 120, "nome": "MATA INSETOS 1 LITRO", "preco": 25.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 125, "nome": "SABONETE LIQUIDO DOVE", "preco": 5.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 133, "nome": "ALCOOL 70 1LITRO", "preco": 11.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 139, "nome": "SABAO LIQUIDO COM QUEROSENE", "preco": 15.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 140, "nome": "DESINFETANTE FLORAL 2 LITROS", "preco": 6.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 142, "nome": "ANTI MOFO 500ML", "preco": 11.00, "imagem": "img/anti500.png", "categoria": "residencial" },
  { "id": 143, "nome": "DESINFETANTE EUCALIPTO 2 LITROS", "preco": 6.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 144, "nome": "NAFTALINA 24G", "preco": 3.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 319, "nome": "ALCOOL PERFUMADO 5 LITROS", "preco": 20.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450001, "nome": "AGUA SANITARIA 2 LITROS", "preco": 6.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450002, "nome": "AGUA SANITARIA 5 LITROS", "preco": 11.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450013, "nome": "ALCOOL PERFUMADO MAÇA E CANELA 2 LITROS", "preco": 10.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450020, "nome": "ALVEJANTE SEM CLORO 2 LITROS", "preco": 11.00, "imagem": "img/alv2.png", "categoria": "residencial" },
  { "id": 789123450061, "nome": "CLORO 2 LITROS", "preco": 15.00, "imagem": "img/cl2lt.png", "categoria": "residencial" },
  { "id": 789123450062, "nome": "CLORO 5 LITROS", "preco": 28.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450070, "nome": "DESINFETANTE MARINE 2 LITROS", "preco": 6.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450074, "nome": "DESINFETANTE CASA LIMPA 2 LITROS", "preco": 6.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450076, "nome": "DESINFETANTE CITRONELA 2 LITROS", "preco": 6.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450089, "nome": "DESINFETANTE KAIAK 2 LITROS", "preco": 6.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450091, "nome": "DESINFETANTE LAVANDA 2 LITROS", "preco": 6.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450102, "nome": "DESINFETANTE TALCO 2 LITROS", "preco": 6.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450108, "nome": "DETERGENTE NEUTRO 2 LITROS", "preco": 10.00, "imagem": "img/det2lt.png", "categoria": "residencial" },
  { "id": 789123450132, "nome": "LIMPA ALUMINIO 1 LITRO", "preco": 10.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450145, "nome": "LIMPA CANIL 2 LITROS", "preco": 10.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450161, "nome": "LIMPA TUDO DESENGORDURANTE 2 LITROS", "preco": 15.00, "imagem": "img/lt2lt.png", "categoria": "residencial" },
  { "id": 789123450226, "nome": "AROMATIZANTE SELVA VERDE", "preco": 10.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450246, "nome": "SABAO LIQUIDO OMUS 2 LITROS", "preco": 14.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450267, "nome": "PEDRA ANTI MOFO 25G", "preco": 4.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450270, "nome": "AMACIANTE MAMAE BEBE 2 LITROS", "preco": 10.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450271, "nome": "ODORIZANTE DE AMBIENTE (BIXINHO)", "preco": 13.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450278, "nome": "CONCENTRADO FLORES DO CAMPO", "preco": 16.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450279, "nome": "CONCENTRADO LAVANDA", "preco": 16.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450280, "nome": "CONCENTRADO CHA BRANCO", "preco": 16.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450281, "nome": "CONCENTRADO TULIPA NEGRA", "preco": 16.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450282, "nome": "CONCENTRADO MARINE", "preco": 16.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450283, "nome": "SABONETE LIQUIDO UVA 500ML C VALVULA", "preco": 6.90, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450288, "nome": "ANIL 500 ML", "preco": 8.00, "imagem": "img/anil500.png", "categoria": "residencial" },
  { "id": 789123450290, "nome": "DETERGENTE LIMAO 2 LITROS", "preco": 10.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450293, "nome": "SABONETE ARTESANAL S CAIXA", "preco": 5.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450294, "nome": "SABONETE ARTESANAL C CAIXA", "preco": 7.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450296, "nome": "SABONETE LIQUIDO PESSEGO 1 LITRO", "preco": 10.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450299, "nome": "DETERGENTE NEUTRO 5 LITROS", "preco": 20.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450300, "nome": "SABAO LIQUIDO ARIEX 5 LITROS", "preco": 29.90, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450301, "nome": "SABAO LIQUIDO DE COCO 5 LITROS", "preco": 29.90, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450302, "nome": "SABAO LIQUIDO OMUS 5 LITROS", "preco": 29.90, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450303, "nome": "AMACIANTE MAMAE BEBE 5 LITROS", "preco": 20.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450304, "nome": "AMACIANTE CONFORTO 5 LITROS", "preco": 20.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450305, "nome": "AMACIANTE DOWNIE 5 LITROS", "preco": 20.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450306, "nome": "DESINFETANTE KAIAK 5 LITROS", "preco": 11.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450307, "nome": "DESINFETANTE FLORAL 5 LITROS", "preco": 11.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450308, "nome": "LIMPA CANIL 5 LITROS", "preco": 20.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450309, "nome": "PROMO CLORO 2X5LTS", "preco": 50.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450310, "nome": "PERCARBONATO DE SODIO 1KG", "preco": 25.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450312, "nome": "DESINFETANTE CAPIM LIMAO 5 LITROS", "preco": 11.50, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450313, "nome": "PERCARBONATO 500GR", "preco": 15.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 789123450315, "nome": "LIMPA ALUMINIO 500ML", "preco": 7.00, "imagem": "img/la500.png", "categoria": "residencial" },
  { "id": 789123450316, "nome": "SABAO LIQUIDO COM BICARBONATO 2 LITROS", "preco": 18.00, "imagem": "img/default.png", "categoria": "residencial" },
  { "id": 79, "nome": "CREOLINA 2LT", "preco": 13.00, "imagem": "img/default.png", "categoria": "industrial" },
  { "id": 124, "nome": "BARRILHA POTE", "preco": 5.00, "imagem": "img/default.png", "categoria": "industrial" },
  { "id": 789123450149, "nome": "LIMPA CANO SUPER 1L", "preco": 20.00, "imagem": "img/default.png", "categoria": "industrial" },
  { "id": 789123450156, "nome": "LIMPA PEDRA 2 LITROS", "preco": 18.00, "imagem": "img/lp2lt.png", "categoria": "industrial" },
  { "id": 789123450285, "nome": "LIMPA PEDRA 5 LITROS", "preco": 39.90, "imagem": "img/default.png", "categoria": "industrial" },
  { "id": 789123450286, "nome": "LIMPA ALUMINIO 5 LITROS", "preco": 39.90, "imagem": "img/default.png", "categoria": "industrial" },
  { "id": 8, "nome": "LIMPA BAU 5 LITROS", "preco": 34.00, "imagem": "img/default.png", "categoria": "automotivo" },
  { "id": 9, "nome": "SOLUPAM 5 LITROS", "preco": 39.90, "imagem": "img/default.png", "categoria": "automotivo" },
  { "id": 14, "nome": "CHEIRINHO PARA CARRO LT", "preco": 2.00, "imagem": "img/default.png", "categoria": "automotivo" },
  { "id": 27, "nome": "SHAMPOO COM CERA 500ML", "preco": 7.00, "imagem": "img/default.png", "categoria": "automotivo" },
  { "id": 46, "nome": "CHEIRINHO PRA CARRO PQ", "preco": 2.00, "imagem": "img/default.png", "categoria": "automotivo" },
  { "id": 63, "nome": "PNEU PRETINHO 500ML", "preco": 8.00, "imagem": "img/default.png", "categoria": "automotivo" },
  { "id": 99, "nome": "AROMATIZANTE VANILLA", "preco": 10.00, "imagem": "img/default.png", "categoria": "automotivo" },
  { "id": 111, "nome": "AROMATIZANTE TROUSARD AZUL", "preco": 10.00, "imagem": "img/default.png", "categoria": "automotivo" },
  { "id": 112, "nome": "AROMATIZANTE MELANCIA", "preco": 10.00, "imagem": "img/default.png", "categoria": "automotivo" },
  { "id": 113, "nome": "SILICONE AUTOMOTIVO 250GR", "preco": 10.00, "imagem": "img/default.png", "categoria": "automotivo" },
  { "id": 114, "nome": "LIMPA PAINEL AUTOMOTIVO 500ML", "preco": 9.90, "imagem": "img/default.png", "categoria": "automotivo" },
  { "id": 115, "nome": "SHAMPOO COM CERA 1 LITRO", "preco": 10.00, "imagem": "img/default.png", "categoria": "automotivo" },
  { "id": 117, "nome": "LIMPA COURO 500ML", "preco": 6.00, "imagem": "img/default.png", "categoria": "automotivo" },
  { "id": 134, "nome": "PNEU PRETINHO 1 LITRO", "preco": 15.00, "imagem": "img/default.png", "categoria": "automotivo" },
  { "id": 789123450143, "nome": "LIMPA BAU 2 LITROS", "preco": 18.00, "imagem": "img/default.png", "categoria": "automotivo" },
  { "id": 789123450277, "nome": "SOLUPAM 2 LITROS", "preco": 14.50, "imagem": "img/default.png", "categoria": "automotivo" },
  { "id": 1, "nome": "VASSOURA VERONA", "preco": 16.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 3, "nome": "BLOCO ESPUMA", "preco": 8.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 10, "nome": "SALADEIRA BACIA COM TAMPA 10 LITROS", "preco": 21.90, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 13, "nome": "GATILHO SPRAY", "preco": 5.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 20, "nome": "BALDE 8 LITROS", "preco": 10.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 25, "nome": "FLANELA PQ", "preco": 2.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 30, "nome": "CASEIRO CASEIRO", "preco": 2.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 36, "nome": "BUCHA INOX ESPONJA AÇO", "preco": 4.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 38, "nome": "BALDE 15 LITROS", "preco": 20.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 43, "nome": "VASSOURA CANTO COLLOR", "preco": 20.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 45, "nome": "VASSOURA ESFREGÃO", "preco": 19.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 49, "nome": "PA DE LIXO COM CABO", "preco": 12.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 50, "nome": "RODO 40 CM PLASTICO", "preco": 18.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 51, "nome": "PANO DE PRATO", "preco": 5.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 52, "nome": "PASSA CERA REFIL", "preco": 13.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 60, "nome": "PANO XADREZ/ALVEJADO ", "preco": 5.90, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 70, "nome": "VASSOURA PIAÇAVA LATA", "preco": 20.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 71, "nome": "CABO AVULSO", "preco": 6.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 74, "nome": "RODO 60CM PLASTICO", "preco": 22.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 78, "nome": "VARAL N10 EXTRA FORTE", "preco": 7.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 81, "nome": "LUVA M", "preco": 9.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 86, "nome": "PA COM CABO", "preco": 9.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 93, "nome": "VASSOURA TROPICANA", "preco": 21.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 94, "nome": "ESCOVA SANITARIA COM SUPORTE", "preco": 9.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 104, "nome": "LUVA P", "preco": 9.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 105, "nome": "LUVA G", "preco": 9.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 106, "nome": "BUCHA LAVA LOUÇAS", "preco": 2.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 107, "nome": "ESCOVA DE ROUPAS PLASTICO", "preco": 6.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 108, "nome": "ESCOVA DE ROUPAS COM ALÇA", "preco": 9.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 109, "nome": "PRENDEDOR DE ROUPA PEQUENO 1DZ", "preco": 3.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 110, "nome": "PRENDEDOR DE ROUPA GRANDE 1DZ", "preco": 4.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 121, "nome": "DESINTUPIDOR PIA", "preco": 6.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 122, "nome": "CESTO TELADO 60 LITROS", "preco": 49.90, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 129, "nome": "VASSOURA BRUXA", "preco": 45.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 130, "nome": "DESINTUPIDOR W.C", "preco": 10.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 136, "nome": "PASTA EM L", "preco": 2.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 141, "nome": "LIMPA VIDROS PLASTICO COM CABO", "preco": 16.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 145, "nome": "FLANELA LARANJA MEDIA", "preco": 4.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 146, "nome": "FLANELA ALVEJADA MEDIA", "preco": 4.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 147, "nome": "PANO MICROFIBRA MEDIA", "preco": 10.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450139, "nome": "LIMPA AZULEJO COM CABO", "preco": 16.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450163, "nome": "VASSOURA SAVANA", "preco": 21.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450195, "nome": "PASSA CERA MADEIRA COM CABO", "preco": 17.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450217, "nome": "VASSOURA POP", "preco": 16.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450225, "nome": "RODO 30CM PLASTICO", "preco": 16.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450256, "nome": "SACO DE LIXO 100 LITROS 10UN", "preco": 12.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450258, "nome": "SACO DE LIXO 100 LITROS 5UN REFORÇADO", "preco": 12.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450261, "nome": "SACO DE LIXO 20 LITROS 10UN", "preco": 5.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450263, "nome": "SACO DE LIXO 40 LITROS 10UN", "preco": 7.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450264, "nome": "SACO DE LIXO 60 LITROS 10UN", "preco": 10.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450266, "nome": "SACO DE LIXO 60 LITROS 5UN REFORÇADO", "preco": 10.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450268, "nome": "VASSOURA RAVENA", "preco": 21.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450269, "nome": "VASSOURA VERONA", "preco": 20.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450272, "nome": "TAPETE 'CIZAL'", "preco": 12.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450284, "nome": "FRASCO COM GATILHO SPRAY", "preco": 8.50, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450287, "nome": "ESCOVA DE ROUPAS MADEIRA", "preco": 5.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450291, "nome": "VASSOURA AQUARELA", "preco": 24.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450295, "nome": "BALDE PEDREIRO", "preco": 21.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450298, "nome": "LIMPA VIDROS SEM CABO", "preco": 15.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450311, "nome": "REGADOR 5 L", "preco": 19.90, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450314, "nome": "VASSOURA PIAÇAVA N4", "preco": 20.00, "imagem": "img/default.png", "categoria": "utilitarios" },
  { "id": 789123450317, "nome": "BACIA 40 LITROS", "preco": 49.90, "imagem": "img/default.png", "categoria": "utilitarios" }
]

produtos.forEach(produto => {
  const nome = produto.nome.toUpperCase();

  if (nome.includes("500ML") || nome.includes("500 ML") || nome.includes("500GR")) {
    produto.imagem = "img/500ml.png";
  } 
  else if (nome.includes("1 LITRO") || nome.includes("1LITRO") || nome.includes("1L")) {
    produto.imagem = "img/1lt.png";
  } 
  else if (nome.includes("2 LITROS") || nome.includes("2LT") || nome.includes("2 LITROS")) {
    produto.imagem = "img/2lt.png";
  } 
  else if (nome.includes("5 LITROS") || nome.includes("5LT") || nome.includes("5 L")) {
    produto.imagem = "img/5lt.png";
  }
});
// Organiza a lista de produtos em ordem alfabética pelo nome
produtos.sort((a, b) => {
    return a.nome.localeCompare(b.nome);
});